[tools]
go = "latest"
node = "20"
"npm:@glint/core" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:neovim" = "latest"
"npm:typescript" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yarn" = "1"
"npm:zx" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
