[tools]
bun = "latest"
deno = "latest"
node = "24"
"npm:@typescript/native-preview" = "latest"
"npm:@typespec/compiler" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:aws-cdk" = "latest"
"npm:commitizen" = "latest"
"npm:fastify-cli" = "latest"
"npm:neovim" = "latest"
"npm:pnpm" = "latest"
"npm:typescript" = "latest"
"npm:vscode-langservers-extracted" = "latest"
python = "3.14"
rust = "latest"
usage = "latest"
uv = "latest"

[settings]
experimental = true

[settings.python]
compile = true
uv_venv_auto = true
